Repository nectgrams-webapp-team/Nect_app, pull requests merged in 2024-11, with the labels that each got.

#51 Issue #50: Requirements for password validation added
  n_app/app/models/member.rb
  n_app/app/views/members/invitations/edit.html.erb
Labels: enhancement

#57 Updated flex wrap of featured articles v.1
  n_app/app/views/homes/top.html.erb
  n_app/bin/bundle
  n_app/bin/dev
  n_app/bin/docker-entrypoint
  n_app/bin/rails
  n_app/bin/rake
  n_app/bin/setup
Labels: bug

#59 Feature 6 & Design-4
  n_app/app/assets/stylesheets/members.scss
  n_app/app/views/layouts/application.html.erb
  n_app/app/views/members/edit.html.erb
  n_app/app/views/members/show.html.erb
Labels: enhancement

#66 Issue #62 - Site Admins Route Update
  .gitignore
  n_app/app/controllers/members/invitations_controller.rb
  n_app/app/controllers/site_admins/base_controller.rb
  n_app/app/controllers/site_admins/carousel_images_controller.rb
  n_app/app/controllers/site_admins/event_histories_controller.rb
  n_app/app/controllers/site_admins/members_manager_controller.rb
  n_app/app/controllers/site_admins_controller.rb
  n_app/app/models/event_history.rb
  n_app/app/views/members/show.html.erb
  n_app/app/views/site_admins/admin_index.erb
  n_app/app/views/site_admins/base/index.html.erb
  n_app/app/views/site_admins/carousel_images/index.html.erb
  n_app/app/views/site_admins/event_histories/_event_form.html.erb
  n_app/app/views/site_admins/event_histories/index.html.erb
  n_app/app/views/site_admins/event_history_editor.html.erb
  n_app/app/views/site_admins/member_editor.html.erb
  n_app/app/views/site_admins/member_statistics.html.erb
  n_app/app/views/site_admins/members_manager/index.html.erb
  n_app/app/views/site_admins/members_manager/statistics.html.erb
  n_app/config/routes.rb
  n_app/public/uploads/home/file/1/Ruby_On_Rails_Logo.svg.png
  n_app/public/uploads/home/file/1/uploaded_carousel_image.jpg
  n_app/public/uploads/home/file/1/uploaded_carousel_image.png
  n_app/public/uploads/home/file/10/Ruby_On_Rails_Logo.svg.png
  n_app/public/uploads/home/file/11/Ruby_On_Rails_Logo.svg.png
  n_app/public/uploads/home/file/12/F3TGiJdSeGTcvD6QVcuWb2Mg.jpg
  n_app/public/uploads/home/file/13/uploaded_carousel_image.png
  n_app/public/uploads/home/file/2/F3TGiJdSeGTcvD6QVcuWb2Mg.jpg
  n_app/public/uploads/home/file/3/Ruby_On_Rails_Logo.svg.png
  n_app/public/uploads/home/file/4/ruby-on-rails-afc3db8e82.png
  n_app/public/uploads/home/file/5/ruby-on-rails-afc3db8e82.png
  n_app/public/uploads/home/file/6/Ruby_On_Rails_Logo.svg.png
  n_app/public/uploads/home/file/7/Ruby_On_Rails_Logo.svg.png
  n_app/public/uploads/home/file/8/ruby-on-rails-afc3db8e82.png
  n_app/public/uploads/home/file/9/uploaded_carousel_image.jpg
Labels: refactor

#61 Design 5 Pull Request
  .gitignore
  .idea/Nect_app.iml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  Gemfile.lock
  n_app/app/assets/stylesheets/activities.scss
  n_app/app/assets/stylesheets/members.scss
  n_app/app/controllers/activities_controller.rb
  n_app/app/views/activities/edit.html.erb
  n_app/app/views/activities/new.html.erb
  n_app/app/views/activities/show.html.erb
  n_app/app/views/members/edit.html.erb
Labels: enhancement, refactor
